---

- name: __defaults__
  folds: 2
  max_runtime_seconds: 60
  cores: 8
  min_vol_size_mb: 16384


- name: jungle_chess_2pcs_raw_endgame_complete
  openml_task_id: 167119
  metric:
    - logloss
    - acc
